FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    golang \
    libbtrfs-dev \
    git-core \
    libdevmapper-dev \
    libgpgme11-dev \
    go-md2man \
    libglib2.0-dev \
    make

ENV GOPATH=/
WORKDIR /src/github.com/containers/skopeo
